[database]
# main postgres db to store transactions for processing
pg_url = "postgresql://localhost:5432/carbon_axelar_execute_relayer"

[carbon]
# bridge id constant specified on carbon
axelar_bridge_id = "axelar"
# specifies whether admin payloads are relayed for free
relay_admin_payloads = true
# specifies whether user payloads are relayed at a cost
relay_user_payloads = true
# carbon's TM RPC URL
rpc_url = "http://localhost:26657"
# carbon's WS URL
ws_url = "ws://localhost:26657/websocket"
# relayer deposit address on carbon we should watch for
relayer_deposit_address = "tswth19cwu2rnstsntezuk23tcf0kq0lu9fc4rjz7085"

[[evm_chain]]
# chain id should be the same as what is found on carbon's connection
chain_id = "bsc-testnet"
# RPC url for broadcasting and resyncing events on EVM
rpc_url = "https://bsc-testnet.publicnode.com"
# WS url for listening to events on EVM
ws_url = ""
# Axelar's main gateway proxy
axelar_gateway_proxy = "0x169ee9364B412B986d09e628eb74e60B2C092729"
# Carbon's SC gateway
carbon_axelar_gateway = "0xCBCBE6c390657f4E40151B6301066fe4FCdd14Ac"
# max_query_blocks is for resyncing, as some chains has a limit on how much you can query at once
max_query_blocks = 10000
# private key to the evm relayer addresss
relayer_private_key = ""