name: Release

on:
  push:
    tags: [ "v*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ext: tar.gz
          - target: x86_64-apple-darwin
            os: macos-latest
            ext: zip

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Setup buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          cd target/${{ matrix.target }}/release

          # Rename binary for consistency
          BIN_NAME=carbon_axelar_execute_relayer
          OUT_NAME=${BIN_NAME}-${{ matrix.target }}.${{ matrix.ext }}

          if [ "${{ matrix.ext }}" = "zip" ]; then
            zip -j ../../../$OUT_NAME $BIN_NAME
          else
            tar -czvf ../../../$OUT_NAME $BIN_NAME
          fi

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: carbon-${{ matrix.target }}
          path: carbon_axelar_execute_relayer-${{ matrix.target }}.${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            artifacts/**/carbon_axelar_execute_relayer-*.*